import GNC.Applications.OrbitalComparison.FullFieldData.STT10Time12.ResidualX
import GNC.Applications.OrbitalComparison.FullFieldData.STT10Time12.ResidualY
import GNC.Applications.OrbitalComparison.FullFieldData.STT10Time12.Constraint

/-! Generated by full_field_certificate.py; the generator is untrusted.
Lean checks the complete physical and inverse-radius constraint defects.
Time degree 12; 600-second powered circle; |pointing| ≤ 7/20 radians.
-/
set_option maxRecDepth 100000
set_option maxHeartbeats 0
set_option Elab.async false

namespace GNC.OrbitalComparison.FullFieldData.STT10Time12
open FullFieldCertificate PoweredCircle Set
open UniformCertificate (curve circleRepresentation polynomialRepresentation)
open WeightedCertificate (circleTime polynomialTime)

private theorem radius_nonnegative :
    0 ≤ data.radius := by decide +kernel

private theorem radius_below_centre :
    data.radius < 7000000 := by decide +kernel

private theorem tube_inside_radius :
    Direct.tubeRadius ≤ data.radius := by decide +kernel

private theorem gravity_gain :
    360000*(2*Direct.gravityParameter/(7000000-data.radius)^3) ≤ 17/20 := by decide +kernel

private theorem offset_nonnegative :
    0 ≤ data.offsetBound := by decide +kernel

private theorem offset_below_one :
    data.offsetBound < 1 := by decide +kernel

private theorem offset_envelope :
    Planning.PolynomialKernel.evaluate (polynomialTime.envelope data.inverseOffset) 1 ≤ data.offsetBound := by decide +kernel

private theorem initial_x :
    polynomialRepresentation.bound data.x 0 = 0 := by decide +kernel

private theorem initial_y :
    polynomialRepresentation.bound data.y 0 = 0 := by decide +kernel

private theorem initial_dx :
    polynomialRepresentation.bound (polynomialRepresentation.derivative data.x) 0 = 0 := by decide +kernel

private theorem initial_dy :
    polynomialRepresentation.bound (polynomialRepresentation.derivative data.y) 0 = 0 := by decide +kernel

private theorem x_starts_quadratic :
    polynomialTime.envelope data.x = 0::0::(polynomialTime.envelope data.x).drop 2 := by decide +kernel

private theorem y_starts_quadratic :
    polynomialTime.envelope data.y = 0::0::(polynomialTime.envelope data.y).drop 2 := by decide +kernel

private theorem position_inside_radius :
    7000000^2*((Planning.PolynomialKernel.evaluate (polynomialTime.envelope data.x) 1)^2+(Planning.PolynomialKernel.evaluate (polynomialTime.envelope data.y) 1)^2) ≤ data.radius^2 := by decide +kernel

private theorem forcing_dominates :
    PolynomialOrder.prefixes 0 (PolynomialBounds.subtract data.forcing (neededForcing polynomialTime data.x data.y data.inverseOffset data.radius data.offsetBound)) := by
  unfold neededForcing
  rw [envelope_x_normalized, envelope_y_normalized, envelope_constraint_normalized]
  decide +kernel

private theorem envelope_valid :
    PolynomialEnvelope.Valid data.forcing data.envelope := by decide +kernel

private theorem position_budget :
    Planning.PolynomialKernel.evaluate data.envelope 1 ≤ data.positionLimit := by decide +kernel

private theorem velocity_budget :
    Planning.PolynomialKernel.evaluate (Planning.PolynomialKernel.differentiate data.envelope) 1/600 ≤ data.velocityLimit := by decide +kernel

theorem valid : data.Valid polynomialTime :=
  ⟨radius_nonnegative, radius_below_centre, tube_inside_radius, gravity_gain, offset_nonnegative, offset_below_one, offset_envelope, initial_x, initial_y, initial_dx, initial_dy, x_starts_quadratic, y_starts_quadratic, position_inside_radius, forcing_dominates, envelope_valid, position_budget, velocity_budget⟩

theorem prediction {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [CompleteSpace E] (B : Plane E) {θ : ℝ}
    (X : PhysicalDeviation B.reference (B.force θ)) (hθ : |θ| ≤ 7/20) :
    ∀ t ∈ Icc (0:ℝ) 1,
      ‖X.p t-(curve polynomialRepresentation data.x data.y θ).position B t‖ ≤ (34873/1000000000000) ∧
      ‖X.v t-(curve polynomialRepresentation data.x data.y θ).velocity B t‖/600 ≤ (9423/12500000000000) := by
  have hp : (data.positionLimit:ℝ) = (34873/1000000000000) := by norm_num [data]
  have hv : (data.velocityLimit:ℝ) = (9423/12500000000000) := by norm_num [data]
  simpa only [hp,hv] using data.certifies polynomialTime valid B X hθ

end GNC.OrbitalComparison.FullFieldData.STT10Time12
