import GNC.Applications.OrbitalComparison.UniformRepresentations

/-! Generated by uniform_certificate.py. The generator and its interval
arithmetic are untrusted. Lean checks the exact rational coefficients and
all comparisons, then applies the physical trajectory error theorem.
Time degree 12; |pointing| ≤ 7/20 radians; all times in a 600-second burn.
-/
set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace GNC.OrbitalComparison.UniformData.Circle
open UniformCertificate PoweredCircle Set

def data : Data (C := CirclePolynomial.Coefficients) where
  x := ⟨[
    [],
    [],
    [0, (-3604995672515079/9223372036854775808)],
    [],
    [0, (7998495654766815/590295810358705651712)],
    [],
    [0, (-6910692233516735/37778931862957161709568), (-5794782164386797/604462909807314587353088)],
    [],
    [0, (-1061636854682173/4835703278458516698824704), (333393131005381/302231454903657293676544)],
    [],
    [0, (696614073725371/19342813113834066795298816), (-1054408568725047/38685626227668133590597632)],
    [],
    [0, (-2877761830189825/4951760157141521099596496896), (7512490557595575/19807040628566084398385987584)]], [
    [],
    [],
    [],
    [(194129016964937/1152921504606846976)],
    [],
    [(-4142672034844359/1180591620717411303424)],
    [],
    [(5291827961764831/151115727451828646838272), (2853019607334665/604462909807314587353088)],
    [],
    [(-7886131051611755/38685626227668133590597632), (-3124254953158235/19342813113834066795298816)],
    [],
    [(7692405162618525/9903520314283042199192993792), (6869527955330431/2475880078570760549798248448)]]⟩
  y := ⟨[
    [],
    [],
    [],
    [0, (194129016964937/1152921504606846976)],
    [],
    [0, (-8285344069688717/2361183241434822606848)],
    [],
    [0, (5707893321167799/151115727451828646838272), (-1307633986695055/604462909807314587353088)],
    [],
    [0, (-6503248878701641/19342813113834066795298816), (3441424383919237/38685626227668133590597632)],
    [],
    [0, (4148712735340465/1237940039285380274899124224), (-8174409095187941/4951760157141521099596496896)]], [
    [],
    [],
    [(3604995672515079/9223372036854775808)],
    [],
    [(-8032312338071593/147573952589676412928)],
    [],
    [(7152047499966639/9444732965739290427392), (-1931594054795599/302231454903657293676544)],
    [],
    [(-3425968735942623/604462909807314587353088), (4530941384900473/9671406556917033397649408)],
    [],
    [(4084432043567395/154742504910672534362390528), (-3420462394709259/309485009821345068724781056)],
    [],
    [(-830020077994997/9903520314283042199192993792), (377090844356623/2475880078570760549798248448)]]⟩
  radius := (261873/200)
  defect := (70929/125000000000000000)
  positionLimit := (433/10000000)
  velocityLimit := (31/200000000)

theorem valid : data.Valid circleRepresentation := by decide +kernel

/-- Uniform physical position and inertial velocity prediction certificate.
The physical trajectory supplies its defining ODE and zero initial error;
the coefficient, radius, defect and budget obligations are all discharged. -/
theorem prediction {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [CompleteSpace E] (B : Plane E) {θ : ℝ}
    (X : PhysicalDeviation B.reference (B.force θ)) (hθ : |θ| ≤ 7/20) :
    ∀ t ∈ Icc (0:ℝ) 1,
      ‖X.p t-(curve circleRepresentation data.x data.y θ).position B t‖ ≤ (433/10000000) ∧
      ‖X.v t-(curve circleRepresentation data.x data.y θ).velocity B t‖/600 ≤ (31/200000000) := by
  have hp : (data.positionLimit:ℝ) = (433/10000000) := by norm_num [data]
  have hv : (data.velocityLimit:ℝ) = (31/200000000) := by norm_num [data]
  simpa only [hp,hv] using data.certifies circleRepresentation valid B X hθ

end GNC.OrbitalComparison.UniformData.Circle
