import GNC.Dynamics.MixedLogLinear
import Mathlib.Analysis.Calculus.Deriv.Shift

/-! A rigorous replacement for an unrestricted power-series ansatz.
A group-affine remainder with zero value and zero first derivatives at
the identity vanishes on the subgroup generated by the exponentials.
The proof uses the functional equation and ODE uniqueness; analyticity
and a convergent expansion of arbitrary smooth functions are not assumed.
-/
noncomputable section
open NormedSpace Set
namespace GNC.Estimation
open MixedInvariant
variable {A : Type*} [NormedRing A] [NormedAlgebra ℝ A] [CompleteSpace A]

theorem group_affine_on_sub (G : Subgroup Aˣ) (f h : A → A)
    (hf : GroupAffineOn G f) (hh : GroupAffineOn G h) :
    GroupAffineOn G (fun X => f X-h X) := by
  intro X hX Y hY
  dsimp only
  rw [hf X hX Y hY, hh X hX Y hY]
  noncomm_ring

/-- The general group-affine field minus its invariant drift obeys the
multiplicative Leibniz identity. It need not be an ambient commutator. -/
theorem group_affine_remove_drift (G : Subgroup Aˣ) (f : A → A)
    (hf : GroupAffineOn G f) (X Y : Aˣ) (hX : X ∈ G) (hY : Y ∈ G) :
    f (X*Y).val-(X*Y).val*f 1 =
      (f X.val-X.val*f 1)*Y.val+X.val*(f Y.val-Y.val*f 1) := by
  rw [hf X hX Y hY]
  simp only [Units.val_mul]
  noncomm_ring

/-- A remainder with zero first derivative along an exponential solves
a homogeneous linear ODE along that entire one-parameter subgroup. -/
theorem remainder_exp_derivative (G : Subgroup Aˣ) (r : A → A)
    (hr : GroupAffineOn G r) (hr₀ : r 1 = 0) (Z : A)
    (hZ : ∀ s : ℝ, expUnit (s • Z) ∈ G)
    (hd₀ : HasDerivAt (fun s : ℝ => r (exp (s • Z))) 0 0) (t : ℝ) :
    HasDerivAt (fun s : ℝ => r (exp (s • Z))) (r (exp (t • Z))*Z) t := by
  letI : NormedAlgebra ℚ A := NormedAlgebra.restrictScalars ℚ ℝ A
  have hadd (s : ℝ) : r (exp ((t+s) • Z)) =
      r (exp (t • Z))*exp (s • Z)+exp (t • Z)*r (exp (s • Z)) := by
    have h := hr (expUnit (t • Z)) (hZ t) (expUnit (s • Z)) (hZ s)
    simp only [Units.val_mul, expUnit_val, hr₀, mul_zero, zero_mul, sub_zero] at h
    rw [add_smul, exp_add_of_commute (((Commute.refl Z).smul_left t).smul_right s)]
    exact h
  have hs : HasDerivAt (fun s : ℝ => r (exp ((t+s) • Z)))
      (r (exp (t • Z))*Z) 0 := by
    simp_rw [hadd]
    simpa using ((hasDerivAt_exp_smul_const Z 0).const_mul (r (exp (t • Z)))).add
      (hd₀.const_mul (exp (t • Z)))
  have ht : HasDerivAt (fun s : ℝ => r (exp ((t+s) • Z)))
      (r (exp (t • Z))*Z) (t-t) := by simpa using hs
  simpa using ht.comp_sub_const t t

theorem remainder_zero_on_exp (G : Subgroup Aˣ) (r : A → A)
    (hr : GroupAffineOn G r) (hr₀ : r 1 = 0) (Z : A)
    (hZ : ∀ s : ℝ, expUnit (s • Z) ∈ G)
    (hd₀ : HasDerivAt (fun s : ℝ => r (exp (s • Z))) 0 0) : r (exp Z) = 0 := by
  have heq : (fun s : ℝ => r (exp (s • Z))) = flow 0 Z 0 := by
    apply flow_unique
    · intro t
      simpa using remainder_exp_derivative G r hr hr₀ Z hZ hd₀ t
    · simpa using hr₀
  have h := congrFun heq 1
  simpa [flow] using h

/-- No additional remainder is possible after its value and first
derivatives have been matched. Exponential generation is explicit; for
connected finite-dimensional Lie groups it is the usual global bridge
from an identity neighborhood, not a surjectivity assumption on exp. -/
theorem zero_first_jet_rigidity (G : Subgroup Aˣ) (𝔤 : Submodule ℝ A)
    (hexp : ∀ Z ∈ 𝔤, expUnit Z ∈ G)
    (hgen : G ≤ Subgroup.closure {X : Aˣ | ∃ Z ∈ 𝔤, expUnit Z = X})
    (r : A → A) (hr : GroupAffineOn G r) (hr₀ : r 1 = 0)
    (hd₀ : ∀ Z ∈ 𝔤, HasDerivAt (fun s : ℝ => r (exp (s • Z))) 0 0) :
    ∀ X ∈ G, r X.val = 0 := by
  let K : Subgroup Aˣ := {
    carrier := {X | X ∈ G ∧ r X.val = 0}
    one_mem' := ⟨G.one_mem, by simpa using hr₀⟩
    mul_mem' := by
      intro X Y hX hY
      refine ⟨G.mul_mem hX.1 hY.1, ?_⟩
      simp only [hr X hX.1 Y hY.1, hX.2, hY.2, hr₀, zero_mul, mul_zero, add_zero,
        sub_zero]
    inv_mem' := by
      intro X hX
      refine ⟨G.inv_mem hX.1, ?_⟩
      have h := hr X hX.1 X⁻¹ (G.inv_mem hX.1)
      simp only [mul_inv_cancel, Units.val_one, hr₀, hX.2, zero_mul, mul_zero,
        zero_add, sub_zero] at h
      have hi := congrArg (fun z : A => (X⁻¹).val*z) h
      simpa only [mul_zero, ← mul_assoc, Units.inv_mul, one_mul] using hi.symm }
  have hk : Subgroup.closure {X : Aˣ | ∃ Z ∈ 𝔤, expUnit Z = X} ≤ K := by
    apply (Subgroup.closure_le K).mpr
    rintro X ⟨Z,hZ,rfl⟩
    exact ⟨hexp Z hZ, remainder_zero_on_exp G r hr hr₀ Z
      (fun s => hexp _ (𝔤.smul_mem s hZ)) (hd₀ Z hZ)⟩
  exact fun X hX => (hk (hgen hX)).2

/-- An exact, group-independent criterion for the existence of a
specified ambient mixed representation. All the state dependence is
determined by its value and first derivatives at the identity. Matching
those derivatives by M and N is a real restriction, not automatic. -/
theorem mixed_representation_iff_first_jet (G : Subgroup Aˣ) (𝔤 : Submodule ℝ A)
    (hexp : ∀ Z ∈ 𝔤, expUnit Z ∈ G)
    (hgen : G ≤ Subgroup.closure {X : Aˣ | ∃ Z ∈ 𝔤, expUnit Z = X})
    (f : A → A) (hf : GroupAffineOn G f) (M N : A) :
    (∀ X ∈ G, f X.val = field M N X.val) ↔
      f 1 = M+N ∧ ∀ Z ∈ 𝔤,
        HasDerivAt (fun s : ℝ => f (exp (s • Z))) (M*Z+Z*N) 0 := by
  have hmodel (Z : A) : HasDerivAt (fun s : ℝ => field M N (exp (s • Z)))
      (M*Z+Z*N) 0 := by
    simpa [field] using ((hasDerivAt_exp_smul_const Z (0:ℝ)).const_mul M).add
      ((hasDerivAt_exp_smul_const Z (0:ℝ)).mul_const N)
  constructor
  · intro heq
    refine ⟨by simpa [field] using heq 1 G.one_mem, ?_⟩
    intro Z hZ
    have hcurve : (fun s : ℝ => f (exp (s • Z))) =
        fun s : ℝ => field M N (exp (s • Z)) := by
      funext s
      exact heq (expUnit (s • Z)) (hexp _ (𝔤.smul_mem s hZ))
    rw [hcurve]
    exact hmodel Z
  · rintro ⟨hf₀,hdf⟩
    have hr := zero_first_jet_rigidity G 𝔤 hexp hgen
      (fun X => f X-field M N X)
      (group_affine_on_sub G f (field M N) hf (field_group_affine_on G M N))
      (by simp [field, hf₀])
      (fun Z hZ => by simpa using (hdf Z hZ).sub (hmodel Z))
    intro X hX
    exact sub_eq_zero.mp (hr X hX)

end GNC.Estimation
