import GNC.Magnus.NilpotentInteraction
import GNC.Magnus.GaussLegendre
import GNC.Dynamics.RotatingVariational
import Mathlib.RingTheory.Nilpotent.Basic
import Mathlib.Algebra.Group.Pi.Units

/-! Where nilpotent termination does and does not apply to the orbital STM.
The retained log generator has a square-zero attitude-to-translation ideal,
but its gravity/kinematic translation block is generally not nilpotent.
Non-nilpotence alone does NOT imply that a particular Magnus series is infinite:
for example, a constant generator always has an exact first Magnus term. -/
noncomputable section
open Matrix Polynomial
namespace GNC.OrbitalNilpotence
variable {n : Type*} [Fintype n] [DecidableEq n]

def translation (G : Matrix n n ℝ) : Matrix (n ⊕ n) (n ⊕ n) ℝ :=
  fromBlocks 0 1 G 0

def coupling (C : Matrix n n ℝ) : Matrix (n ⊕ n) n ℝ := Sum.elim 0 C

def generator (G W C : Matrix n n ℝ) : Matrix ((n ⊕ n) ⊕ n) ((n ⊕ n) ⊕ n) ℝ :=
  fromBlocks (RotatingVariational.logGenerator G W) (coupling C) 0 (-W)

omit [Fintype n] in
/-- Orbital state order (position, velocity, attitude), C = minus thrust hat. -/
theorem generator_split (G W C : Matrix n n ℝ) :
    generator G W C = fromBlocks (RotatingVariational.logGenerator G W) 0 0 (-W) +
      NilpotentInteraction.lift (coupling C) := by
  simp [generator, NilpotentInteraction.lift, fromBlocks_add]

theorem translation_square (G : Matrix n n ℝ) :
    translation G ^ 2 = fromBlocks G 0 0 G := by
  simp [translation, pow_two, fromBlocks_multiply]

/-- The feedback loop repeats: even powers contain powers of the gravity gradient. -/
theorem translation_even_power (G : Matrix n n ℝ) (k : ℕ) :
    translation G ^ (2*k) = fromBlocks (G^k) 0 0 (G^k) := by
  rw [pow_mul, translation_square, fromBlocks_diagonal_pow]

theorem translation_unit (G : (Matrix n n ℝ)ˣ) : IsUnit (translation G.val) := by
  refine ⟨⟨translation G.val, fromBlocks 0 (G⁻¹).val 1 0, ?_, ?_⟩, rfl⟩ <;>
    simp [translation, fromBlocks_multiply, fromBlocks_one]

/-- A nonsingular gravity gradient rules out terminating the exponential Taylor series. -/
theorem translation_not_nilpotent [Nonempty n] (G : (Matrix n n ℝ)ˣ) :
    ¬ IsNilpotent (translation G.val) := (translation_unit G).not_isNilpotent

/-- The central-gravity gradient in an RTN frame is nonsingular at nonzero mu/r^3. -/
theorem central_gradient_unit (c : ℝ) (hc : c ≠ 0) :
    IsUnit (diagonal ![2*c, -c, -c]) := by
  rw [isUnit_diagonal, Pi.isUnit_iff]
  intro i; fin_cases i <;> simp [hc]

theorem central_translation_not_nilpotent (c : ℝ) (hc : c ≠ 0) :
    ¬ IsNilpotent (translation (diagonal ![2*c, -c, -c])) := by
  obtain ⟨G,hG⟩ := central_gradient_unit c hc
  rw [← hG]
  exact translation_not_nilpotent G

def drift : Matrix (n ⊕ n) (n ⊕ n) ℝ := fromBlocks 0 1 0 0
def gravity (G : Matrix n n ℝ) : Matrix (n ⊕ n) (n ⊕ n) ℝ := fromBlocks 0 0 G 0

/-- Each of these generators is square-zero, but their mixed products need not vanish. -/
theorem separate_squares (G : Matrix n n ℝ) :
    (drift (n := n))^2 = 0 ∧ gravity G ^ 2 = 0 := by
  constructor <;> simp [drift, gravity, pow_two, fromBlocks_multiply, fromBlocks_zero]

theorem drift_gravity_commutator (G : Matrix n n ℝ) :
    drift * gravity G - gravity G * drift = fromBlocks G 0 0 (-G) := by
  ext i j; rcases i with i | i <;> rcases j with j | j <;>
    simp [drift, gravity, fromBlocks_multiply]

/-- Arbitrarily repeated adjoints survive in the algebra generated by kinematics
and a gravity block. Thus separate nilpotence does not force Magnus termination. -/
theorem repeated_commutator (k : ℕ) :
    let C : Matrix (n ⊕ n) (n ⊕ n) ℝ := fromBlocks 1 0 0 (-1)
    (fun X => C*X-X*C)^[k] drift = (2^k : ℝ) • drift (n := n) := by
  dsimp only
  have hC (r : ℝ) :
      fromBlocks 1 0 0 (-1) * (r • drift (n := n)) -
        (r • drift (n := n)) * fromBlocks 1 0 0 (-1) = (2*r) • drift := by
    ext i j; rcases i with i | i <;> rcases j with j | j <;>
      simp [drift, fromBlocks_multiply, two_mul] <;> ring
  induction k with
  | zero => simp
  | succ k ih =>
    rw [Function.iterate_succ_apply', ih, hC]
    congr 1; ring

theorem repeated_commutator_ne_zero [Nonempty n] (k : ℕ) :
    let C : Matrix (n ⊕ n) (n ⊕ n) ℝ := fromBlocks 1 0 0 (-1)
    (fun X => C*X-X*C)^[k] drift ≠ 0 := by
  have hr := repeated_commutator (n := n) k
  dsimp only at hr ⊢
  rw [hr]
  intro h
  obtain ⟨i⟩ := ‹Nonempty n›
  have he := congrArg (fun X : Matrix (n ⊕ n) (n ⊕ n) ℝ => X (.inl i) (.inr i)) h
  simpa [drift] using he

/-! A transported lower-block correction remains pointwise square-zero.
That is insufficient: its values at different times can generate arbitrarily
deep nonzero commutators. This free-drift example rules out an inference of
Magnus termination from pointwise nilpotence alone; it does not claim that
every coefficient of every particular Magnus series is nonzero. -/
def freeDrift2 (t : ℝ) : Matrix (Fin 2) (Fin 2) ℝ := !![1, t; 0, 1]
/-- Lower-block correction transported by the free-drift fundamental flow. -/
def transportedGravity2 (t : ℝ) : Matrix (Fin 2) (Fin 2) ℝ := !![-t, -(t^2); 1, t]

theorem freeDrift2_inverse (t : ℝ) :
    freeDrift2 (-t) * freeDrift2 t = 1 ∧ freeDrift2 t * freeDrift2 (-t) = 1 := by
  constructor <;> ext i j <;> fin_cases i <;> fin_cases j <;>
    simp [freeDrift2, Matrix.mul_apply, Fin.sum_univ_two]

theorem transportedGravity2_conjugate (t : ℝ) :
    freeDrift2 (-t) * !![0, 0; 1, 0] * freeDrift2 t = transportedGravity2 t := by
  ext i j; fin_cases i <;> fin_cases j <;>
    simp [freeDrift2, transportedGravity2, Matrix.mul_apply, Fin.sum_univ_two] <;> ring

theorem transportedGravity2_square (t : ℝ) : transportedGravity2 t ^ 2 = 0 := by
  ext i j; fin_cases i <;> fin_cases j <;>
    simp [transportedGravity2, pow_two, Matrix.mul_apply, Fin.sum_univ_two] <;> ring

theorem transportedGravity2_commutator_entry (t s : ℝ) :
    (transportedGravity2 t * transportedGravity2 s -
      transportedGravity2 s * transportedGravity2 t) 1 0 = 2*(t-s) := by
  simp [transportedGravity2]; ring

theorem transportedGravity2_noncommute {t s : ℝ} (h : t ≠ s) :
    transportedGravity2 t * transportedGravity2 s ≠
      transportedGravity2 s * transportedGravity2 t := by
  intro he
  have he' := transportedGravity2_commutator_entry t s
  rw [he, sub_self] at he'
  simp only [Matrix.zero_apply] at he'
  apply h
  linarith

def transportedGravity2Bracket : Matrix (Fin 2) (Fin 2) ℝ :=
    transportedGravity2 0 * transportedGravity2 1 -
      transportedGravity2 1 * transportedGravity2 0

theorem transportedGravity2_bracket_action (r : ℝ) :
    transportedGravity2Bracket * (r • transportedGravity2 0) -
      (r • transportedGravity2 0) * transportedGravity2Bracket =
        (-2*r) • transportedGravity2 0 := by
  ext i j; fin_cases i <;> fin_cases j <;>
    simp [transportedGravity2Bracket, transportedGravity2] <;> ring

theorem transportedGravity2_repeated (k : ℕ) :
    (fun X => transportedGravity2Bracket*X-X*transportedGravity2Bracket)^[k]
      (transportedGravity2 0) = ((-2:ℝ)^k) • transportedGravity2 0 := by
  induction k with
  | zero => simp
  | succ k ih =>
    rw [Function.iterate_succ_apply', ih, transportedGravity2_bracket_action]
    congr 1
    ring

theorem transportedGravity2_repeated_ne_zero (k : ℕ) :
    (fun X => transportedGravity2Bracket*X-X*transportedGravity2Bracket)^[k]
      (transportedGravity2 0) ≠ 0 := by
  rw [transportedGravity2_repeated]
  intro h
  have he := congrArg (fun X : Matrix (Fin 2) (Fin 2) ℝ => X 1 0) h
  simp [transportedGravity2] at he

/-- Explicit link between the conjugated gravity correction and its cubic-jet inputs. -/
theorem transportedGravity2_polynomial (t : ℝ) :
    transportedGravity2 t = !![0, 0; 1, 0] +
      t • !![-1, 0; 0, 1] + t^2 • !![0, -1; 0, 0] := by
  ext i j; fin_cases i <;> fin_cases j <;> simp [transportedGravity2]

/-- The first formal Magnus integral already misses the cubic lower-left
flow coefficient. Pointwise square-zero transport does not justify keeping
only that integral. This statement concerns exact formal coefficients. -/
theorem transported_first_integral_cubic_mismatch :
    let a : Matrix (Fin 2) (Fin 2) ℝ := !![0, 0; 1, 0]
    let b : Matrix (Fin 2) (Fin 2) ℝ := !![-1, 0; 0, 1]
    let c : Matrix (Fin 2) (Fin 2) ℝ := !![0, -1; 0, 0]
    let firstIntegral := monomial 1 a + monomial 2 ((1/2:ℝ) • b) +
      monomial 3 ((1/3:ℝ) • c)
    (Magnus.expCoeff firstIntegral 3 - Magnus.leftFlowCoeff a b c 0 3) 1 0 = -1/6 := by
  norm_num [Magnus.expCoeff, Magnus.leftFlowCoeff, pow_succ, Polynomial.coeff_mul,
    Polynomial.coeff_monomial, Polynomial.coeff_one,
    Finset.Nat.sum_antidiagonal_eq_sum_range_succ_mk, Finset.sum_range_succ,
    Matrix.mul_apply, Fin.sum_univ_two]

end GNC.OrbitalNilpotence
