import GNC.Applications.OrbitalComparison.CenteredResponseData.Linear00
import GNC.Applications.OrbitalComparison.CenteredResponseData.Linear01
import GNC.Applications.OrbitalComparison.CenteredResponseData.Linear02
import GNC.Applications.OrbitalComparison.CenteredResponseData.Linear03
import GNC.Applications.OrbitalComparison.CenteredResponseData.Linear04
import GNC.Applications.OrbitalComparison.CenteredResponseData.Linear05
import GNC.Applications.OrbitalComparison.CenteredResponseData.Linear06
import GNC.Applications.OrbitalComparison.CenteredResponseData.Linear07
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic00
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic01
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic02
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic03
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic04
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic05
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic06
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic07
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic08
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic09
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic10
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic11
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic12
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic13
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic14
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic15
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic16
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic17
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic18
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic19
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic20
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic21
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic22
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic23
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic24
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic25
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic26
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic27
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic28
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic29
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic30
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic31
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic32
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic33
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic34
import GNC.Applications.OrbitalComparison.CenteredResponseData.Quadratic35

/-! Generated by centered_response_export.py. Stored time coefficients are
untrusted proposals. Kernel checks cover their actual polynomial residuals
throughout [0,1], without an integration tolerance. Physical phase and
trajectory composition remain separate obligations. -/
set_option maxHeartbeats 0
set_option maxRecDepth 100000
set_option Elab.async false
namespace GNC.OrbitalComparison.CenteredResponseData
open CartesianResponsePolynomial Matrix Set

theorem all_linear_checked : ∀ j,
    bound (linearResidual K reference (first j) (sources j))≤firstBudget j := by
  intro j
  fin_cases j
  · exact linear00_checked
  · exact linear01_checked
  · exact linear02_checked
  · exact linear03_checked
  · exact linear04_checked
  · exact linear05_checked
  · exact linear06_checked
  · exact linear07_checked

theorem all_quadratic_checked : ∀ j,
    bound (quadraticResidual K (factor j) reference
      (first (pairLeft j)) (first (pairRight j)) (second j))≤secondBudget j := by
  intro j
  fin_cases j
  · exact quadratic00_checked
  · exact quadratic01_checked
  · exact quadratic02_checked
  · exact quadratic03_checked
  · exact quadratic04_checked
  · exact quadratic05_checked
  · exact quadratic06_checked
  · exact quadratic07_checked
  · exact quadratic08_checked
  · exact quadratic09_checked
  · exact quadratic10_checked
  · exact quadratic11_checked
  · exact quadratic12_checked
  · exact quadratic13_checked
  · exact quadratic14_checked
  · exact quadratic15_checked
  · exact quadratic16_checked
  · exact quadratic17_checked
  · exact quadratic18_checked
  · exact quadratic19_checked
  · exact quadratic20_checked
  · exact quadratic21_checked
  · exact quadratic22_checked
  · exact quadratic23_checked
  · exact quadratic24_checked
  · exact quadratic25_checked
  · exact quadratic26_checked
  · exact quadratic27_checked
  · exact quadratic28_checked
  · exact quadratic29_checked
  · exact quadratic30_checked
  · exact quadratic31_checked
  · exact quadratic32_checked
  · exact quadratic33_checked
  · exact quadratic34_checked
  · exact quadratic35_checked

def linearDefect : ℚ := (1821007449/24178516392292583494123520)
def quadraticDefect : ℚ := (590005954241/241785163922925834941235200)

theorem linear_budget_checked : (1/20:ℚ)*(∑ j, firstBudget j)=linearDefect := by decide +kernel
theorem quadratic_budget_checked : (1/400:ℚ)*(∑ j, secondBudget j)=quadraticDefect := by decide +kernel

theorem combined_linear_residual (w : Fin 8 → ℝ) (hw : ∀ j, |w j|≤1/20)
    {t : ℝ} (ht : t ∈ Icc (0:ℝ) 1) :
    enorm (combination (fun j => linearResidual K reference (first j) (sources j)) w t)≤
      (linearDefect:ℝ) := by
  have h := combination_bound (fun j => linearResidual K reference (first j) (sources j))
    w firstBudget (r := 1/20) (by norm_num) (by simpa using hw) all_linear_checked ht
  simpa only [linear_budget_checked] using h

theorem combined_quadratic_residual (w : Fin 8 → ℝ) (hw : ∀ j, |w j|≤1/20)
    {t : ℝ} (ht : t ∈ Icc (0:ℝ) 1) :
    enorm (combination (fun j => quadraticResidual K (factor j) reference
      (first (pairLeft j)) (first (pairRight j)) (second j))
      (fun j => w (pairLeft j)*w (pairRight j)) t)≤(quadraticDefect:ℝ) := by
  have hw' (j : Fin 36) : |w (pairLeft j)*w (pairRight j)|≤((1/400:ℚ):ℝ) := by
    rw [abs_mul]
    have h := mul_le_mul (hw (pairLeft j)) (hw (pairRight j)) (abs_nonneg _)
      (by norm_num : (0:ℝ)≤1/20)
    norm_num at h ⊢
    exact h
  have h := combination_bound (fun j => quadraticResidual K (factor j) reference
      (first (pairLeft j)) (first (pairRight j)) (second j))
    (fun j => w (pairLeft j)*w (pairRight j)) secondBudget (r := 1/400)
    (by norm_num) hw' all_quadratic_checked ht
  simpa only [quadratic_budget_checked] using h

end GNC.OrbitalComparison.CenteredResponseData
