import GNC.Applications.OrbitalComparison.FullFieldData.Circle12
import GNC.Applications.OrbitalComparison.FullFieldData.STT10Time12

/-! Selected external Flow* reports confirmed by the stronger independent
full-field certificates. This does NOT verify Flow* code or its internal
proof construction. Cycle measurements are not formal performance theorems.
Generated by the flowstar report tooling in the companion papers repository.
-/
noncomputable section
namespace GNC.OrbitalComparison.FlowstarReportedBounds
open PoweredCircle UniformCertificate Set

def circlePosition : ℚ := (1847302962428441/18889465931478580854784)
def circleVelocity : ℚ := (2335981593109983/2417851639229258349412352)

theorem circle_prediction {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [CompleteSpace E] (B : Plane E) {θ : ℝ}
    (X : PhysicalDeviation B.reference (B.force θ)) (hθ : |θ| ≤ 7/20) :
    ∀ t ∈ Icc (0:ℝ) 1,
      ‖X.p t-(curve circleRepresentation FullFieldData.Circle12.data.x
        FullFieldData.Circle12.data.y θ).position B t‖ ≤ (circlePosition:ℝ) ∧
      ‖X.v t-(curve circleRepresentation FullFieldData.Circle12.data.x
        FullFieldData.Circle12.data.y θ).velocity B t‖/600 ≤ (circleVelocity:ℝ) := by
  intro t ht
  have h := FullFieldData.Circle12.prediction B X hθ t ht
  exact ⟨h.1.trans (by norm_num [circlePosition]), h.2.trans (by norm_num [circleVelocity])⟩

def sttPosition : ℚ := (6680871188649257/75557863725914323419136)
def sttVelocity : ℚ := (2372475960303515/2417851639229258349412352)

theorem stt_prediction {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [CompleteSpace E] (B : Plane E) {θ : ℝ}
    (X : PhysicalDeviation B.reference (B.force θ)) (hθ : |θ| ≤ 7/20) :
    ∀ t ∈ Icc (0:ℝ) 1,
      ‖X.p t-(curve polynomialRepresentation FullFieldData.STT10Time12.data.x
        FullFieldData.STT10Time12.data.y θ).position B t‖ ≤ (sttPosition:ℝ) ∧
      ‖X.v t-(curve polynomialRepresentation FullFieldData.STT10Time12.data.x
        FullFieldData.STT10Time12.data.y θ).velocity B t‖/600 ≤ (sttVelocity:ℝ) := by
  intro t ht
  have h := FullFieldData.STT10Time12.prediction B X hθ t ht
  exact ⟨h.1.trans (by norm_num [sttPosition]), h.2.trans (by norm_num [sttVelocity])⟩

theorem common_targets :
    (circlePosition:ℝ) ≤ 1/10000000 ∧ (circleVelocity:ℝ) ≤ 1/1000000000 ∧
    (sttPosition:ℝ) ≤ 1/10000000 ∧ (sttVelocity:ℝ) ≤ 1/1000000000 := by
  norm_num [circlePosition,circleVelocity,sttPosition,sttVelocity]

end GNC.OrbitalComparison.FlowstarReportedBounds
