import GNC.Magnus.FOHIncrement

/-! Exact conversion between endpoint-defined linear inputs and the two
equal-subinterval increments used by classical coning/sculling formulas.
These are equalities of the retained exponent corrections, not an assertion
that every classical navigation update equals the full group exponential.
The position identity is a first time moment; complete rotating scrolling
also includes products generated by the exponential. -/
noncomputable section
namespace GNC.Magnus
open Matrix

def halfFirst (T : ℝ) (u s : Vec3) : Vec3 := (T/2) • u+(T^2/8) • s
def halfSecond (T : ℝ) (u s : Vec3) : Vec3 := (T/2) • u+(3*T^2/8) • s

theorem half_sum (T : ℝ) (u s : Vec3) :
    halfFirst T u s+halfSecond T u s = T • u+(T^2/2) • s := by
  unfold halfFirst halfSecond
  module

theorem two_sample_coning (T : ℝ) (w s : Vec3) :
    (2/3 : ℝ) • crossProduct (halfFirst T w s) (halfSecond T w s) =
      (T^3/12) • crossProduct w s := by
  ext i
  fin_cases i <;> simp [halfFirst, halfSecond, crossProduct, vecHead, vecTail] <;> ring

theorem two_sample_sculling (T : ℝ) (w s a b : Vec3) :
    (2/3 : ℝ) • (crossProduct (halfFirst T w s) (halfSecond T a b)+
      crossProduct (halfFirst T a b) (halfSecond T w s)) =
      (T^3/12) • (crossProduct w b-crossProduct s a) := by
  ext i
  fin_cases i <;> simp [halfFirst, halfSecond, crossProduct, vecHead, vecTail] <;> ring

theorem two_sample_position_moment (T : ℝ) (a b : Vec3) :
    (T/3) • (halfFirst T a b-halfSecond T a b) = -(T^3/12) • b := by
  unfold halfFirst halfSecond
  module

theorem nonrotating_displacement (T : ℝ) (a b : Vec3) :
    (T/2) • (halfFirst T a b+halfSecond T a b)+
      (T/3) • (halfFirst T a b-halfSecond T a b) =
      (T^2/2) • a+(T^3/6) • b := by
  unfold halfFirst halfSecond
  module

end GNC.Magnus
