import GNC.Applications.OrbitalComparison.SpatialExactNominal
import GNC.Applications.OrbitalComparison.RotatingBernsteinData.Liftedjet4CircleTime12Inverse10

/-! Generated by exact_nominal_certificate.py; Lean checks the result.
Reuse the existing coefficient certificate without rebuilding its arithmetic.
Subtract the analytic physical nominal, with uniqueness proved in GNC.
-/
namespace GNC.OrbitalComparison.ExactNominalData.Liftedjet4CircleTime12Inverse10
open Set SpatialRotatingCertificate
open RotatingBernsteinData.Liftedjet4CircleTime12Inverse10 (data valid)

theorem relative_prediction {θ : ℝ}
    (X : SpatialFieldCertificate.PhysicalOrbit .rtnReferenceOffset θ)
    (X₀ : SpatialFieldCertificate.PhysicalOrbit .rtnReferenceOffset 0)
    (hθ : |θ| ≤ 7/20) :
    ∀ t ∈ Icc (0:ℝ) 1,
      ‖(X.p t-X₀.p t)-(position SpatialSources.circle data.q θ t-SpatialExactNominal.nominal.p t)‖ ≤
        (42533/62500000000) ∧
      ‖(X.v t-X₀.v t)-(velocity SpatialSources.circle data.q θ t-SpatialExactNominal.nominal.v t)‖/600 ≤
        (1323/125000000000) := by
  have hp : (data.positionLimit:ℝ) = (42533/62500000000) := by norm_num [data]
  have hv : (data.velocityLimit:ℝ) = (1323/125000000000) := by norm_num [data]
  simpa only [hp,hv] using SpatialExactNominal.relative_certifies
    SpatialSources.circle WeightedCertificate.circleBernsteinTime data valid X X₀
    (show |θ| ≤ (UniformCertificate.angle:ℝ) by simpa [UniformCertificate.angle] using hθ)

end GNC.OrbitalComparison.ExactNominalData.Liftedjet4CircleTime12Inverse10
