import GNC.Applications.OrbitalComparison.CenteredResponseData.Transfer
import GNC.Applications.OrbitalComparison.HarmonicCertificate
import GNC.Analysis.PolynomialForcing

/-! Generated by centered_response_export.py. Stored time coefficients are
untrusted proposals. Kernel checks cover their actual polynomial residuals
throughout [0,1], without an integration tolerance. Physical phase and
trajectory composition remain separate obligations. -/
set_option maxHeartbeats 0
set_option maxRecDepth 100000
set_option Elab.async false
namespace GNC.OrbitalComparison.CenteredResponseData
open CartesianResponsePolynomial Matrix Set

open Planning.PolynomialKernel

def firstRange : ℚ := (217082009430165979487/151115727451828646838272)
def secondRange : ℚ := (63687542394186105/1208925819614629174706176)
def displacementRange : ℚ := firstRange+secondRange
def firstInitialRadius : ℚ := (1/10)^2/8
def firstInitialSpeed : ℚ := (1/10)^2*(3231/25000)/8
def inputMagnitude : ℚ := forceFactor/20
def responseGain : ℚ := 2*K
def physicalGain : ℚ := (20405845019484496974277/604462909807314587353088)
def defectMagnitude : ℚ := (250834199848233/1208925819614629174706176)
def forcing : List ℚ := [defectMagnitude]
def physicalEnvelope : List ℚ := [0,0,(250834199848233/2417851639229258349412352),0,(1706161269229814776624362740368300847/5846006549323611672814739330865132078623730171904),0,(34815662438150563798443301301025330439760168977975156312619/106010823886703059774997850044575110949649033812537137487296372077557186560),0,(710443011963588160967239308619551390310094953849610571834974030682301021813501463/3586294979904509010647581047676265606250039552651921763455304985582652258471626358648670549243330560)]
def positionUpper : ℚ := (182061/250000000)
def velocityUpper : ℚ := (12171517/1000000000000)

theorem response_data_nonnegative : 0 ≤ responseGain ∧ responseGain < 2 ∧
    0 ≤ firstInitialRadius ∧ 0 ≤ firstInitialSpeed ∧ 0 ≤ inputMagnitude ∧
    0 ≤ firstDefect ∧ 0 ≤ secondDefect := by decide +kernel
theorem first_range_checked : firstInitialRadius+firstInitialSpeed+
    (responseGain*(firstInitialRadius+firstInitialSpeed)+inputMagnitude+firstDefect)/
      (2-responseGain)≤firstRange := by decide +kernel
theorem second_range_checked :
    (3*K*firstRange^2+secondDefect)/(2-responseGain)≤secondRange := by decide +kernel
theorem region_checked : 0≤firstRange ∧ 0≤secondRange ∧ 0<displacementRange ∧
    2*displacementRange<1 := by decide +kernel
theorem gravity_gain_checked : 0≤physicalGain ∧ physicalGain<56 ∧
    2*K/(1-2*displacementRange)^3≤physicalGain ∧ physicalGain≤1 := by decide +kernel
theorem physical_budget_checked :
    firstDefect+secondDefect+3*K*secondRange*(2*firstRange+secondRange)+
      4*K*displacementRange^3/(1-displacementRange)^5≤defectMagnitude := by decide +kernel
theorem physical_envelope_checked :
    PolynomialForcing.Valid physicalGain forcing physicalEnvelope := by decide +kernel
theorem physical_closure_checked :
    evaluate forcing 1*HarmonicCertificate.positionGain physicalGain<displacementRange := by decide +kernel
theorem physical_existence_checked :
    4*evaluate forcing 1≤displacementRange/2 := by decide +kernel
theorem physical_display_checked : 7000000*evaluate physicalEnvelope 1≤positionUpper ∧
    (7000000/120)*evaluate (differentiate physicalEnvelope) 1≤velocityUpper := by decide +kernel

end GNC.OrbitalComparison.CenteredResponseData
