import GNC.Applications.OrbitalComparison.CenteredResponseData.Input

/-! Generated by centered_response_export.py. Stored time coefficients are
untrusted proposals. Kernel checks cover their actual polynomial residuals
throughout [0,1], without an integration tolerance. Physical phase and
trajectory composition remain separate obligations. -/
set_option maxHeartbeats 0
set_option maxRecDepth 100000
set_option Elab.async false
namespace GNC.OrbitalComparison.CenteredResponseData
open CartesianResponsePolynomial Matrix Set

theorem linear05_checked :
    bound (linearResidual K reference (first 5) (sources 5))≤firstBudget 5 := by decide +kernel

theorem linear05_residual {t : ℝ} (ht : t ∈ Icc (0:ℝ) 1) :
    enorm (value (linearResidual K reference (first 5) (sources 5)) t)≤(firstBudget 5:ℝ) := by
  exact (value_bound _ ht).trans (by exact_mod_cast linear05_checked)

end GNC.OrbitalComparison.CenteredResponseData
