import GNC.Applications.OrbitalComparison.CenteredResponseData.Input

/-! Generated by centered_response_export.py. Stored time coefficients are
untrusted proposals. Kernel checks cover their actual polynomial residuals
throughout [0,1], without an integration tolerance. Physical phase and
trajectory composition remain separate obligations. -/
set_option maxHeartbeats 0
set_option maxRecDepth 100000
set_option Elab.async false
namespace GNC.OrbitalComparison.CenteredResponseData
open CartesianResponsePolynomial Matrix Set

theorem linear04_checked :
    bound (linearResidual K reference (first 4) (sources 4))≤firstBudget 4 := by decide +kernel

theorem linear04_residual {t : ℝ} (ht : t ∈ Icc (0:ℝ) 1) :
    enorm (value (linearResidual K reference (first 4) (sources 4)) t)≤(firstBudget 4:ℝ) := by
  exact (value_bound _ ht).trans (by exact_mod_cast linear04_checked)

end GNC.OrbitalComparison.CenteredResponseData
