import GNC.Applications.OrbitalComparison.CenteredResponseData.Input

/-! Generated by centered_response_export.py. Stored time coefficients are
untrusted proposals. Kernel checks cover their actual polynomial residuals
throughout [0,1], without an integration tolerance. Physical phase and
trajectory composition remain separate obligations. -/
set_option maxHeartbeats 0
set_option maxRecDepth 100000
set_option Elab.async false
namespace GNC.OrbitalComparison.CenteredResponseData
open CartesianResponsePolynomial Matrix Set

theorem quadratic04_checked :
    bound (quadraticResidual K (factor 4) reference
    (first (pairLeft 4)) (first (pairRight 4)) (second 4))≤secondBudget 4 := by decide +kernel

theorem quadratic04_residual {t : ℝ} (ht : t ∈ Icc (0:ℝ) 1) :
    enorm (value (quadraticResidual K (factor 4) reference
    (first (pairLeft 4)) (first (pairRight 4)) (second 4)) t)≤(secondBudget 4:ℝ) := by
  exact (value_bound _ ht).trans (by exact_mod_cast quadratic04_checked)

end GNC.OrbitalComparison.CenteredResponseData
