import GNC.Applications.OrbitalComparison.CenteredResponseData.Input

/-! Generated by centered_response_export.py. Stored time coefficients are
untrusted proposals. Kernel checks cover their actual polynomial residuals
throughout [0,1], without an integration tolerance. Physical phase and
trajectory composition remain separate obligations. -/
set_option maxHeartbeats 0
set_option maxRecDepth 100000
set_option Elab.async false
namespace GNC.OrbitalComparison.CenteredResponseData
open CartesianResponsePolynomial Matrix Set

theorem quadratic28_checked :
    bound (quadraticResidual K (factor 28) reference
    (first (pairLeft 28)) (first (pairRight 28)) (second 28))≤secondBudget 28 := by decide +kernel

theorem quadratic28_residual {t : ℝ} (ht : t ∈ Icc (0:ℝ) 1) :
    enorm (value (quadraticResidual K (factor 28) reference
    (first (pairLeft 28)) (first (pairRight 28)) (second 28)) t)≤(secondBudget 28:ℝ) := by
  exact (value_bound _ ht).trans (by exact_mod_cast quadratic28_checked)

end GNC.OrbitalComparison.CenteredResponseData
