import GNC.Applications.OrbitalComparison.CenteredResponseData.Input

/-! Generated by centered_response_export.py. Stored time coefficients are
untrusted proposals. Kernel checks cover their actual polynomial residuals
throughout [0,1], without an integration tolerance. Physical phase and
trajectory composition remain separate obligations. -/
set_option maxHeartbeats 0
set_option maxRecDepth 100000
set_option Elab.async false
namespace GNC.OrbitalComparison.CenteredResponseData
open CartesianResponsePolynomial Matrix Set

theorem quadratic12_checked :
    bound (quadraticResidual K (factor 12) reference
    (first (pairLeft 12)) (first (pairRight 12)) (second 12))≤secondBudget 12 := by decide +kernel

theorem quadratic12_residual {t : ℝ} (ht : t ∈ Icc (0:ℝ) 1) :
    enorm (value (quadraticResidual K (factor 12) reference
    (first (pairLeft 12)) (first (pairRight 12)) (second 12)) t)≤(secondBudget 12:ℝ) := by
  exact (value_bound _ ht).trans (by exact_mod_cast quadratic12_checked)

end GNC.OrbitalComparison.CenteredResponseData
