import GNC.Applications.OrbitalComparison.CenteredResponseData.Input

/-! Generated by centered_response_export.py. Stored time coefficients are
untrusted proposals. Kernel checks cover their actual polynomial residuals
throughout [0,1], without an integration tolerance. Physical phase and
trajectory composition remain separate obligations. -/
set_option maxHeartbeats 0
set_option maxRecDepth 100000
set_option Elab.async false
namespace GNC.OrbitalComparison.CenteredResponseData
open CartesianResponsePolynomial Matrix Set

theorem quadratic25_checked :
    bound (quadraticResidual K (factor 25) reference
    (first (pairLeft 25)) (first (pairRight 25)) (second 25))≤secondBudget 25 := by decide +kernel

theorem quadratic25_residual {t : ℝ} (ht : t ∈ Icc (0:ℝ) 1) :
    enorm (value (quadraticResidual K (factor 25) reference
    (first (pairLeft 25)) (first (pairRight 25)) (second 25)) t)≤(secondBudget 25:ℝ) := by
  exact (value_bound _ ht).trans (by exact_mod_cast quadratic25_checked)

end GNC.OrbitalComparison.CenteredResponseData
