import GNC.Applications.OrbitalComparison.CenteredResponseData.Input
import GNC.Analysis.PolynomialPhaseCertificate

/-! Generated by centered_response_export.py. Stored time coefficients are
untrusted proposals. Kernel checks cover their actual polynomial residuals
throughout [0,1], without an integration tolerance. Physical phase and
trajectory composition remain separate obligations. -/
set_option maxHeartbeats 0
set_option maxRecDepth 100000
set_option Elab.async false
namespace GNC.OrbitalComparison.CenteredResponseData
open CartesianResponsePolynomial Matrix Set

def phaseError : ℚ := (13025139698094014625436388229540956445775577016673/23492798209190368652343750000000000000000000000000000000000000000000000000)
def phaseData : PolynomialPhaseCertificate.Data where
  rate := [(3231/25000),(1/200000)]
  cosine := reference 0
  sine := reference 1
  error := phaseError

theorem phase_checked : PolynomialPhaseCertificate.Valid phaseData := by decide +kernel
theorem K_nonnegative : 0≤K := by decide +kernel
theorem phase_nonnegative : 0≤phaseError := by decide +kernel

def gradientError : ℚ := (110882300771815218014602376824437920565874382792591805856444955681859410082652403584793042653639368924531572039619481131861613867651/1991852564397350588976109975192230194807052612304687500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)
def halfHessianError : ℚ := (4688883930605415094114380988315718890817831472458129476995167473579814295731927010307392445051645359967848674968281300444752684931196690822979755228092436294499991416588336984354084267629270854847642345123/18717676143138128547757927084795774932968193127180711599066853523254394531250000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)
def forceFactor : ℚ := (2576669379/68600000000000)
def firstCoarseRadius : ℚ := (56908534932179594022200552943282191359459/332306998946228968225951765070086144000000)
def secondCoarseRadius : ℚ := (1006762073238832058068082063102313/3323069989462289682259517650700861440)
def firstDefect : ℚ := (91050373/1208925819614629174706176)
def secondDefect : ℚ := (737507443/302231454903657293676544)

theorem gradient_budget_checked : 3*K*phaseError*(2+phaseError)=gradientError := by decide +kernel
theorem hessian_budget_checked :
    K*phaseError*(9+15*(1+(1+phaseError)+(1+phaseError)^2))/2=halfHessianError := by decide +kernel
theorem first_coarse_checked : (1/20:ℚ)*(∑ j, bound (first j))≤firstCoarseRadius := by decide +kernel
theorem second_coarse_checked : (1/400:ℚ)*(∑ j, bound (second j))≤secondCoarseRadius := by decide +kernel
theorem first_transfer_budget_checked :
    (1/20:ℚ)*(∑ j, firstBudget j)+gradientError*firstCoarseRadius+
      (1/20)*forceFactor*phaseError≤firstDefect := by decide +kernel
theorem second_transfer_budget_checked :
    (1/400:ℚ)*(∑ j, secondBudget j)+gradientError*secondCoarseRadius+
      halfHessianError*firstCoarseRadius^2≤secondDefect := by decide +kernel

def radialPolynomial : List ℚ := [(16757883/535937500000),(-3231/2500000000),(-1/40000000000)]
def slope : ℚ := (1/200000)
def forcePolynomial : Vector :=
  ![PolynomialBounds.subtract (PolynomialBounds.multiply radialPolynomial (reference 0))
      (PolynomialBounds.scale slope (reference 1)),
    PolynomialBounds.add (PolynomialBounds.multiply radialPolynomial (reference 1))
      (PolynomialBounds.scale slope (reference 0)), []]
def featureRow : Fin 8 → Fin 3 := ![0,0,0,1,1,1,2,2]
def featureColumn : Fin 8 → Fin 3 := ![0,1,2,0,1,2,0,1]

theorem source_coefficients_checked : ∀ j i,
    BernsteinPolynomial.zero (PolynomialBounds.subtract (sources j i)
      (if i=featureRow j then forcePolynomial (featureColumn j) else [])) := by decide +kernel

theorem radial_formula_checked : BernsteinPolynomial.zero
    (PolynomialBounds.subtract radialPolynomial
      (PolynomialBounds.subtract [K]
        (PolynomialBounds.multiply phaseData.rate phaseData.rate))) := by decide +kernel
theorem force_factor_checked : PolynomialBounds.bound radialPolynomial 1+slope=forceFactor := by decide +kernel
theorem slope_nonnegative : 0≤slope := by decide +kernel

end GNC.OrbitalComparison.CenteredResponseData
