import GNC.Applications.OrbitalComparison.JointErrorData.ConstraintInputs

/-! Generated by joint_error_radius.py. Exact rational identities and
full-ball ranges are kernel checked. Physical closure is separate. -/
set_option maxHeartbeats 0
set_option maxRecDepth 100000
set_option Elab.async false
namespace GNC.OrbitalComparison.JointErrorData
open ParameterPolynomial BallPolynomialEnclosure DegreeProductCertificate


def constraintPart0 : Coefficients := []

theorem constraintPart0_checked : zero (subtract
    (add (constraintBase 0) (scale 1 (degreeProduct 0 radiusPartition offsetSquare)))
    constraintPart0) := by
  decide +kernel

end GNC.OrbitalComparison.JointErrorData
