import GNC.Applications.OrbitalComparison.JointErrorData.Radius
import GNC.Applications.OrbitalComparison.JointErrorData.OffsetSquare

/-! Generated by joint_error_radius.py. Exact rational identities and
full-ball ranges are kernel checked. Physical closure is separate. -/
set_option maxHeartbeats 0
set_option maxRecDepth 100000
set_option Elab.async false
namespace GNC.OrbitalComparison.JointErrorData
open ParameterPolynomial BallPolynomialEnclosure DegreeProductCertificate


def constraintBase : Fin 9 → Coefficients := ![constant (-1),[],[],[],[],[],[],[],[]]

theorem constraintBase_value (x : Fin 3 → ℝ) (t : ℝ) :
    value (assemble constraintBase) x t= -1 := by
  rw [assemble_value]
  simp [constraintBase,Fin.sum_univ_succ,constant,
    ParameterPolynomial.value,termValue,monomial,PolynomialOrder.value,
    Planning.PolynomialKernel.evaluate]

end GNC.OrbitalComparison.JointErrorData
