import GNC.Analysis.DegreeProductCertificate
import GNC.Applications.OrbitalComparison.JointErrorData.OffsetSquare

/-! Generated by joint_error_cubic.py. The kernel checks the degree-eight
enclosure of the actual candidate's full cubic inverse-radius factor.
Higher-degree products are bounded, not assumed to vanish. This component
alone does not certify the complete physical prediction. -/
set_option maxHeartbeats 0
set_option maxRecDepth 100000
set_option Elab.async false
namespace GNC.OrbitalComparison.JointErrorData
open ParameterPolynomial BallPolynomialEnclosure


def offsetCubePart1 : Coefficients := [⟨0,0,1,[0,0,(17708874310761171/4722366482869645213696),(-19083658883723265/9444732965739290427392),(9447590515153959/604462909807314587353088),(8144824634261607/4835703278458516698824704),(-655611325640559/77371252455336267181195264),(-13345881777323301/19807040628566084398385987584),(808252419371217/316912650057057350374175801344),(12722637220595541/81129638414606681695789005144064),(-19929441909939609/41538374868278621028243970633760768),(-3968703431574249/166153499473114484112975882535043072),(21044951003176959/340282366920938463463374607431768211456)]⟩]

theorem offsetCubePart1_checked : zero (subtract
    (DegreeProductCertificate.degreeProduct 1 offsetSquare oneOffset)
    offsetCubePart1) := by
  decide +kernel

end GNC.OrbitalComparison.JointErrorData
