import GNC.Analysis.DegreeProductCertificate
import GNC.Applications.OrbitalComparison.JointErrorData.OffsetSquare

/-! Generated by joint_error_cubic.py. The kernel checks the degree-eight
enclosure of the actual candidate's full cubic inverse-radius factor.
Higher-degree products are bounded, not assumed to vanish. This component
alone does not certify the complete physical prediction. -/
set_option maxHeartbeats 0
set_option maxRecDepth 100000
set_option Elab.async false
namespace GNC.OrbitalComparison.JointErrorData
open ParameterPolynomial BallPolynomialEnclosure


def offsetCubePart0 : Coefficients := [⟨0,0,0,[1]⟩]

theorem offsetCubePart0_checked : zero (subtract
    (DegreeProductCertificate.degreeProduct 0 offsetSquare oneOffset)
    offsetCubePart0) := by
  decide +kernel

end GNC.OrbitalComparison.JointErrorData
