import GNC.Analysis.BallPolynomialEnclosure
import GNC.Applications.OrbitalComparison.JointErrorData.OffsetCubeData

/-! Generated by joint_error_cubic.py. The kernel checks the degree-eight
enclosure of the actual candidate's full cubic inverse-radius factor.
Higher-degree products are bounded, not assumed to vanish. This component
alone does not certify the complete physical prediction. -/
set_option maxHeartbeats 0
set_option maxRecDepth 100000
set_option Elab.async false
namespace GNC.OrbitalComparison.JointErrorData
open ParameterPolynomial BallPolynomialEnclosure


/-- The retained record has the advertised total attitude degree. -/
theorem offsetCube_degree : ∀ a ∈ offsetCube, a.u+a.v+a.c≤8 := by
  decide +kernel

/-- Covers every time and attitude in the ball, including all discarded
products of degrees nine through twelve. It is linked to the actual input h. -/
theorem offsetCube_bound {x : Fin 3 → ℝ} {t : ℝ}
    (hx : x 0^2+x 1^2+x 2^2≤((1/10:ℚ):ℝ)^2) (ht : 0≤t) :
    |(1+value inverseOffset x t)^3-value offsetCube x t|≤
      PolynomialOrder.value offsetCubeTail t := by
  have h := truncation_bound 8 offsetSquare oneOffset offsetSquare_checked
    oneOffset_checked hx ht
  rw [offsetSquare_value,oneOffset_value,offsetCube_core_value] at h
  have he := PolynomialOrder.value_nonnegative _ offsetCube_tail_checked ht
  rw [PolynomialOrder.value_subtract] at he
  have hc : (1+value inverseOffset x t)^3=
      (1+value inverseOffset x t)^2*(1+value inverseOffset x t) := by ring
  rw [hc]
  exact h.trans (sub_nonneg.mp he)

/-- Optional uniform-in-time bound derived from the checked time profile. -/
theorem offsetCube_uniform {x : Fin 3 → ℝ} {t : ℝ}
    (hx : x 0^2+x 1^2+x 2^2≤((1/10:ℚ):ℝ)^2) (ht : t ∈ Set.Icc (0:ℝ) 1) :
    |(1+value inverseOffset x t)^3-value offsetCube x t|≤
      PolynomialOrder.value offsetCubeTail 1 :=
  (offsetCube_bound hx ht.1).trans
    (PolynomialOrder.value_le_endpoint _ offsetCube_tail_nonnegative ht)

end GNC.OrbitalComparison.JointErrorData
