import GNC.Analysis.BallPolynomialEnclosure
import GNC.Applications.OrbitalComparison.JointErrorData.OffsetCubePieces
import GNC.Applications.OrbitalComparison.JointErrorData.OffsetCubeTail

/-! Generated by joint_error_cubic.py. The kernel checks the degree-eight
enclosure of the actual candidate's full cubic inverse-radius factor.
Higher-degree products are bounded, not assumed to vanish. This component
alone does not certify the complete physical prediction. -/
set_option maxHeartbeats 0
set_option maxRecDepth 100000
set_option Elab.async false
namespace GNC.OrbitalComparison.JointErrorData
open ParameterPolynomial BallPolynomialEnclosure


def offsetCube : Coefficients := DegreeProductCertificate.assemble offsetCubePieces

theorem offsetCube_core_value (x : Fin 3 → ℝ) (t : ℝ) :
    value (retainedProduct 8 offsetSquare oneOffset) x t=value offsetCube x t := by
  exact DegreeProductCertificate.checked_value 8 offsetSquare oneOffset
    offsetCubePieces offsetCubePieces_checked x t

end GNC.OrbitalComparison.JointErrorData
