import GNC.Applications.OrbitalComparison.JointErrorData.RadiusInputs

/-! Generated by joint_error_radius.py. Exact rational identities and
full-ball ranges are kernel checked. Physical closure is separate. -/
set_option maxHeartbeats 0
set_option maxRecDepth 100000
set_option Elab.async false
namespace GNC.OrbitalComparison.JointErrorData
open ParameterPolynomial BallPolynomialEnclosure DegreeProductCertificate


def radiusPart0 : Coefficients := [⟨0,0,0,[1]⟩]

theorem radiusPart0_checked : zero (subtract
    (add (radiusBasePieces 0) (sumProductDegree 0 radiusLeft radiusRight)) radiusPart0) := by
  decide +kernel

end GNC.OrbitalComparison.JointErrorData
