import GNC.Applications.OrbitalComparison.JointErrorData.RadiusBase
import GNC.Applications.OrbitalComparison.JointErrorData.RadiusFactor0
import GNC.Applications.OrbitalComparison.JointErrorData.RadiusFactor1
import GNC.Applications.OrbitalComparison.JointErrorData.RadiusFactor2
import GNC.Applications.OrbitalComparison.JointErrorData.RadiusCoefficient0
import GNC.Applications.OrbitalComparison.JointErrorData.RadiusCoefficient1
import GNC.Applications.OrbitalComparison.JointErrorData.RadiusCoefficient2

/-! Generated by joint_error_radius.py. Exact rational identities and
full-ball ranges are kernel checked. Physical closure is separate. -/
set_option maxHeartbeats 0
set_option maxRecDepth 100000
set_option Elab.async false
namespace GNC.OrbitalComparison.JointErrorData
open ParameterPolynomial BallPolynomialEnclosure DegreeProductCertificate


def radiusLeft : Fin 3 → Partition := ![radiusCoefficient0,radiusCoefficient1,radiusCoefficient2]
def radiusRight : Fin 3 → Partition := ![radiusFactor0,radiusFactor1,radiusFactor2]

theorem radiusLeft_checked : ∀ i, (radiusLeft i).Valid (mkRat (1) 10) := by
  intro i
  fin_cases i
  · exact radiusCoefficient0_checked
  · exact radiusCoefficient1_checked
  · exact radiusCoefficient2_checked

theorem radiusRight_checked : ∀ i, (radiusRight i).Valid (mkRat (1) 10) := by
  intro i
  fin_cases i
  · exact radiusFactor0_checked
  · exact radiusFactor1_checked
  · exact radiusFactor2_checked

theorem radiusLeft_value (i : Fin 3) (x : Fin 3 → ℝ) (t : ℝ) :
    value (radiusLeft i).core x t=value (JointErrorPolynomial.radiusCoefficients i) x t := by
  fin_cases i
  · exact radiusCoefficient0_value x t
  · exact radiusCoefficient1_value x t
  · exact radiusCoefficient2_value x t

theorem radiusRight_value (i : Fin 3) (x : Fin 3 → ℝ) (t : ℝ) :
    value (radiusRight i).core x t=value (modelInput.radiusFactors i) x t := by
  fin_cases i
  · exact radiusFactor0_value x t
  · exact radiusFactor1_value x t
  · exact radiusFactor2_value x t

end GNC.OrbitalComparison.JointErrorData
