import GNC.Applications.OrbitalComparison.JointErrorData.RadiusPart0

/-! Generated by joint_error_radius.py. Exact rational identities and
full-ball ranges are kernel checked. Physical closure is separate. -/
set_option maxHeartbeats 0
set_option maxRecDepth 100000
set_option Elab.async false
namespace GNC.OrbitalComparison.JointErrorData
open ParameterPolynomial BallPolynomialEnclosure DegreeProductCertificate

def radiusDegree0Range0 : DiskTimePolynomial.Certificate 1 where
  count := 1
  terms := ![⟨0,0,0,⟨![[1]],[1]⟩,1⟩]

def radiusDegree0 : BallPolynomialEnclosure.Partition where
  count := 1
  blocks := ![⟨0,radiusPart0,radiusDegree0Range0⟩]

theorem radiusDegree0_checked : radiusDegree0.Valid (mkRat (1) 10) := by
  intro i
  fin_cases i
  all_goals
    constructor
    · intro k
      fin_cases k
      all_goals refine ⟨checked_scalarProfile _ _ (by decide +kernel), ?_, ?_⟩ <;> decide +kernel
    · intro j
      fin_cases j <;> decide +kernel


end GNC.OrbitalComparison.JointErrorData
