import GNC.Applications.OrbitalComparison.JointRadiusCertificate
import GNC.Applications.OrbitalComparison.JointErrorData.Model

/-! Generated by joint_error_radius.py. Exact rational identities and
full-ball ranges are kernel checked. Physical closure is separate. -/
set_option maxHeartbeats 0
set_option maxRecDepth 100000
set_option Elab.async false
namespace GNC.OrbitalComparison.JointErrorData
open ParameterPolynomial BallPolynomialEnclosure DegreeProductCertificate

def radiusCoefficient0Range0 : DiskTimePolynomial.Certificate 1 where
  count := 1
  terms := ![⟨0,0,0,⟨![[(mkRat (1) 2)]],[(mkRat (1) 2)]⟩,1⟩]

def radiusCoefficient0Range2 : DiskTimePolynomial.Certificate 1 where
  count := 3
  terms := ![⟨0,0,2,⟨![[(mkRat (-1) 24)]],[(mkRat (1) 24)]⟩,(mkRat (1) 100)⟩,
⟨0,2,0,⟨![[(mkRat (-1) 24)]],[(mkRat (1) 24)]⟩,(mkRat (1) 100)⟩,
⟨2,0,0,⟨![[(mkRat (-1) 24)]],[(mkRat (1) 24)]⟩,(mkRat (1) 100)⟩]

def radiusCoefficient0Range4 : DiskTimePolynomial.Certificate 1 where
  count := 6
  terms := ![⟨0,0,4,⟨![[(mkRat (1) 720)]],[(mkRat (1) 720)]⟩,(mkRat (1) 10000)⟩,
⟨0,2,2,⟨![[(mkRat (1) 360)]],[(mkRat (1) 360)]⟩,(mkRat (1) 40000)⟩,
⟨0,4,0,⟨![[(mkRat (1) 720)]],[(mkRat (1) 720)]⟩,(mkRat (1) 10000)⟩,
⟨2,0,2,⟨![[(mkRat (1) 360)]],[(mkRat (1) 360)]⟩,(mkRat (1) 40000)⟩,
⟨2,2,0,⟨![[(mkRat (1) 360)]],[(mkRat (1) 360)]⟩,(mkRat (1) 40000)⟩,
⟨4,0,0,⟨![[(mkRat (1) 720)]],[(mkRat (1) 720)]⟩,(mkRat (1) 10000)⟩]

def radiusCoefficient0Range6 : DiskTimePolynomial.Certificate 1 where
  count := 10
  terms := ![⟨0,0,6,⟨![[(mkRat (-1) 40320)]],[(mkRat (1) 40320)]⟩,(mkRat (1) 1000000)⟩,
⟨0,2,4,⟨![[(mkRat (-1) 13440)]],[(mkRat (1) 13440)]⟩,(mkRat (89550060712194753681939) 604462909807314587353088000000)⟩,
⟨0,4,2,⟨![[(mkRat (-1) 13440)]],[(mkRat (1) 13440)]⟩,(mkRat (89550060712194753681939) 604462909807314587353088000000)⟩,
⟨0,6,0,⟨![[(mkRat (-1) 40320)]],[(mkRat (1) 40320)]⟩,(mkRat (1) 1000000)⟩,
⟨2,0,4,⟨![[(mkRat (-1) 13440)]],[(mkRat (1) 13440)]⟩,(mkRat (89550060712194753681939) 604462909807314587353088000000)⟩,
⟨2,2,2,⟨![[(mkRat (-1) 6720)]],[(mkRat (1) 6720)]⟩,(mkRat (4477503035609737684097) 120892581961462917470617600000)⟩,
⟨2,4,0,⟨![[(mkRat (-1) 13440)]],[(mkRat (1) 13440)]⟩,(mkRat (89550060712194753681939) 604462909807314587353088000000)⟩,
⟨4,0,2,⟨![[(mkRat (-1) 13440)]],[(mkRat (1) 13440)]⟩,(mkRat (89550060712194753681939) 604462909807314587353088000000)⟩,
⟨4,2,0,⟨![[(mkRat (-1) 13440)]],[(mkRat (1) 13440)]⟩,(mkRat (89550060712194753681939) 604462909807314587353088000000)⟩,
⟨6,0,0,⟨![[(mkRat (-1) 40320)]],[(mkRat (1) 40320)]⟩,(mkRat (1) 1000000)⟩]

def radiusCoefficient0 : BallPolynomialEnclosure.Partition where
  count := 4
  blocks := ![⟨0,[⟨0,0,0,[(mkRat (1) 2)]⟩],radiusCoefficient0Range0⟩,
⟨2,[⟨0,0,2,[(mkRat (-1) 24)]⟩,⟨0,2,0,[(mkRat (-1) 24)]⟩,⟨2,0,0,[(mkRat (-1) 24)]⟩],radiusCoefficient0Range2⟩,
⟨4,[⟨0,0,4,[(mkRat (1) 720)]⟩,⟨0,2,2,[(mkRat (1) 360)]⟩,⟨0,4,0,[(mkRat (1) 720)]⟩,⟨2,0,2,[(mkRat (1) 360)]⟩,⟨2,2,0,[(mkRat (1) 360)]⟩,⟨4,0,0,[(mkRat (1) 720)]⟩],radiusCoefficient0Range4⟩,
⟨6,[⟨0,0,6,[(mkRat (-1) 40320)]⟩,⟨0,2,4,[(mkRat (-1) 13440)]⟩,⟨0,4,2,[(mkRat (-1) 13440)]⟩,⟨0,6,0,[(mkRat (-1) 40320)]⟩,⟨2,0,4,[(mkRat (-1) 13440)]⟩,⟨2,2,2,[(mkRat (-1) 6720)]⟩,⟨2,4,0,[(mkRat (-1) 13440)]⟩,⟨4,0,2,[(mkRat (-1) 13440)]⟩,⟨4,2,0,[(mkRat (-1) 13440)]⟩,⟨6,0,0,[(mkRat (-1) 40320)]⟩],radiusCoefficient0Range6⟩]

theorem radiusCoefficient0_checked : radiusCoefficient0.Valid (mkRat (1) 10) := by
  intro i
  fin_cases i
  all_goals
    constructor
    · intro k
      fin_cases k
      all_goals refine ⟨checked_scalarProfile _ _ (by decide +kernel), ?_, ?_⟩ <;> decide +kernel
    · intro j
      fin_cases j <;> decide +kernel


theorem radiusCoefficient0_identity : zero (subtract radiusCoefficient0.core (JointErrorPolynomial.radiusCoefficients 0)) := by
  decide +kernel

theorem radiusCoefficient0_value (x : Fin 3 → ℝ) (t : ℝ) :
    value radiusCoefficient0.core x t=value (JointErrorPolynomial.radiusCoefficients 0) x t :=
  ParameterPolynomial.identity _ _ radiusCoefficient0_identity x t

end GNC.OrbitalComparison.JointErrorData
