import GNC.Applications.OrbitalComparison.JointRadiusCertificate
import GNC.Applications.OrbitalComparison.JointErrorData.Model

/-! Generated by joint_error_radius.py. Exact rational identities and
full-ball ranges are kernel checked. Physical closure is separate. -/
set_option maxHeartbeats 0
set_option maxRecDepth 100000
set_option Elab.async false
namespace GNC.OrbitalComparison.JointErrorData
open ParameterPolynomial BallPolynomialEnclosure DegreeProductCertificate

def radiusCoefficient1Range0 : DiskTimePolynomial.Certificate 1 where
  count := 1
  terms := ![⟨0,0,0,⟨![[(mkRat (1) 6)]],[(mkRat (1) 6)]⟩,1⟩]

def radiusCoefficient1Range2 : DiskTimePolynomial.Certificate 1 where
  count := 3
  terms := ![⟨0,0,2,⟨![[(mkRat (-1) 120)]],[(mkRat (1) 120)]⟩,(mkRat (1) 100)⟩,
⟨0,2,0,⟨![[(mkRat (-1) 120)]],[(mkRat (1) 120)]⟩,(mkRat (1) 100)⟩,
⟨2,0,0,⟨![[(mkRat (-1) 120)]],[(mkRat (1) 120)]⟩,(mkRat (1) 100)⟩]

def radiusCoefficient1Range4 : DiskTimePolynomial.Certificate 1 where
  count := 6
  terms := ![⟨0,0,4,⟨![[(mkRat (1) 5040)]],[(mkRat (1) 5040)]⟩,(mkRat (1) 10000)⟩,
⟨0,2,2,⟨![[(mkRat (1) 2520)]],[(mkRat (1) 2520)]⟩,(mkRat (1) 40000)⟩,
⟨0,4,0,⟨![[(mkRat (1) 5040)]],[(mkRat (1) 5040)]⟩,(mkRat (1) 10000)⟩,
⟨2,0,2,⟨![[(mkRat (1) 2520)]],[(mkRat (1) 2520)]⟩,(mkRat (1) 40000)⟩,
⟨2,2,0,⟨![[(mkRat (1) 2520)]],[(mkRat (1) 2520)]⟩,(mkRat (1) 40000)⟩,
⟨4,0,0,⟨![[(mkRat (1) 5040)]],[(mkRat (1) 5040)]⟩,(mkRat (1) 10000)⟩]

def radiusCoefficient1Range6 : DiskTimePolynomial.Certificate 1 where
  count := 10
  terms := ![⟨0,0,6,⟨![[(mkRat (-1) 362880)]],[(mkRat (1) 362880)]⟩,(mkRat (1) 1000000)⟩,
⟨0,2,4,⟨![[(mkRat (-1) 120960)]],[(mkRat (1) 120960)]⟩,(mkRat (89550060712194753681939) 604462909807314587353088000000)⟩,
⟨0,4,2,⟨![[(mkRat (-1) 120960)]],[(mkRat (1) 120960)]⟩,(mkRat (89550060712194753681939) 604462909807314587353088000000)⟩,
⟨0,6,0,⟨![[(mkRat (-1) 362880)]],[(mkRat (1) 362880)]⟩,(mkRat (1) 1000000)⟩,
⟨2,0,4,⟨![[(mkRat (-1) 120960)]],[(mkRat (1) 120960)]⟩,(mkRat (89550060712194753681939) 604462909807314587353088000000)⟩,
⟨2,2,2,⟨![[(mkRat (-1) 60480)]],[(mkRat (1) 60480)]⟩,(mkRat (4477503035609737684097) 120892581961462917470617600000)⟩,
⟨2,4,0,⟨![[(mkRat (-1) 120960)]],[(mkRat (1) 120960)]⟩,(mkRat (89550060712194753681939) 604462909807314587353088000000)⟩,
⟨4,0,2,⟨![[(mkRat (-1) 120960)]],[(mkRat (1) 120960)]⟩,(mkRat (89550060712194753681939) 604462909807314587353088000000)⟩,
⟨4,2,0,⟨![[(mkRat (-1) 120960)]],[(mkRat (1) 120960)]⟩,(mkRat (89550060712194753681939) 604462909807314587353088000000)⟩,
⟨6,0,0,⟨![[(mkRat (-1) 362880)]],[(mkRat (1) 362880)]⟩,(mkRat (1) 1000000)⟩]

def radiusCoefficient1 : BallPolynomialEnclosure.Partition where
  count := 4
  blocks := ![⟨0,[⟨0,0,0,[(mkRat (1) 6)]⟩],radiusCoefficient1Range0⟩,
⟨2,[⟨0,0,2,[(mkRat (-1) 120)]⟩,⟨0,2,0,[(mkRat (-1) 120)]⟩,⟨2,0,0,[(mkRat (-1) 120)]⟩],radiusCoefficient1Range2⟩,
⟨4,[⟨0,0,4,[(mkRat (1) 5040)]⟩,⟨0,2,2,[(mkRat (1) 2520)]⟩,⟨0,4,0,[(mkRat (1) 5040)]⟩,⟨2,0,2,[(mkRat (1) 2520)]⟩,⟨2,2,0,[(mkRat (1) 2520)]⟩,⟨4,0,0,[(mkRat (1) 5040)]⟩],radiusCoefficient1Range4⟩,
⟨6,[⟨0,0,6,[(mkRat (-1) 362880)]⟩,⟨0,2,4,[(mkRat (-1) 120960)]⟩,⟨0,4,2,[(mkRat (-1) 120960)]⟩,⟨0,6,0,[(mkRat (-1) 362880)]⟩,⟨2,0,4,[(mkRat (-1) 120960)]⟩,⟨2,2,2,[(mkRat (-1) 60480)]⟩,⟨2,4,0,[(mkRat (-1) 120960)]⟩,⟨4,0,2,[(mkRat (-1) 120960)]⟩,⟨4,2,0,[(mkRat (-1) 120960)]⟩,⟨6,0,0,[(mkRat (-1) 362880)]⟩],radiusCoefficient1Range6⟩]

theorem radiusCoefficient1_checked : radiusCoefficient1.Valid (mkRat (1) 10) := by
  intro i
  fin_cases i
  all_goals
    constructor
    · intro k
      fin_cases k
      all_goals refine ⟨checked_scalarProfile _ _ (by decide +kernel), ?_, ?_⟩ <;> decide +kernel
    · intro j
      fin_cases j <;> decide +kernel


theorem radiusCoefficient1_identity : zero (subtract radiusCoefficient1.core (JointErrorPolynomial.radiusCoefficients 1)) := by
  decide +kernel

theorem radiusCoefficient1_value (x : Fin 3 → ℝ) (t : ℝ) :
    value radiusCoefficient1.core x t=value (JointErrorPolynomial.radiusCoefficients 1) x t :=
  ParameterPolynomial.identity _ _ radiusCoefficient1_identity x t

end GNC.OrbitalComparison.JointErrorData
